import { useEffect, useMemo, useState } from "react";
import { CalendarPlus, Loader2, Save } from "lucide-react";
import JSZip from "jszip";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import SlideTextEditor from "@/components/social/SlideTextEditor";
import SaveShareButtons from "@/components/social/SaveShareButtons";
import { pesquisarDual } from "@/lib/dualResearch";
import { renderCarouselCientifico } from "@/lib/carouselCientificoTemplate";
import CarouselInput from "@/components/social-on/carousel-engine/CarouselInput";
import CarouselPreview from "@/components/social-on/carousel-engine/CarouselPreview";
import CarouselScores from "@/components/social-on/carousel-engine/CarouselScores";
import CarouselHistory from "@/components/social-on/carousel-engine/CarouselHistory";
import { nicheToDomain, type CarouselEngineContent, type CarouselEngineSlide, type CarouselHistoryRow, type CarouselNiche, type CarouselScore, type CarouselTone } from "@/components/social-on/carousel-engine/carousel-engine.types";

const json = (v:unknown) => JSON.stringify(v);
const getUser = async()=>{const {data}=await supabase.auth.getUser();if(!data.user)throw new Error("Entre na sua conta para continuar.");return data.user;};

export default function CarouselCientificoPanel({ handle }: { handle?:string|null }) {
 const [topic,setTopic]=useState(""); const [niche,setNiche]=useState<CarouselNiche>("treino"); const [tone,setTone]=useState<CarouselTone>("cientifico"); const [loading,setLoading]=useState(false); const [content,setContent]=useState<CarouselEngineContent|null>(null); const [images,setImages]=useState<string[]>([]); const [history,setHistory]=useState<CarouselHistoryRow[]>([]); const [editing,setEditing]=useState(false); const [regenerating,setRegenerating]=useState<number|null>(null); const [score,setScore]=useState<CarouselScore|null>(null);
 const labels=useMemo(()=>images.map((_,i)=>({url:images[i],filename:`carrossel-cientifico-${i+1}.png`})),[images]);
 const loadHistory=async()=>{const {data}=await (supabase as any).from("social_carousel_history").select("*").order("created_at",{ascending:false}).limit(20);setHistory((data||[]) as CarouselHistoryRow[]);};
 useEffect(()=>{void loadHistory();},[]);
 useEffect(()=>{if(!content)return;let live=true;renderCarouselCientifico(content,handle||"diogo.mell0").then(x=>live&&setImages(x));return()=>{live=false};},[content,handle]);
 const scoreContent=async(next:CarouselEngineContent)=>{try{const {data}=await supabase.functions.invoke("social-on-generate",{body:{mode:"content_score",format:"carousel",content:json(next.slides)}});const s=(data?.result||null) as CarouselScore|null;setScore(s);setContent(v=>v?{...v,score:s}:v);return s;}catch{return null;}};
 const generate=async()=>{if(!topic.trim())return;setLoading(true);try{const research=await pesquisarDual({tema:topic.trim(),dominio:nicheToDomain[niche],angulo:`Carrossel de cinco slides. Tom ${tone}.`});const {data,error}=await supabase.functions.invoke("social-on-generate",{body:{mode:"carousel_engine",topic:topic.trim(),niche,tone,handle,pesquisa:research}});if(error)throw error;const result=data?.result as {slides:CarouselEngineSlide[];caption?:string;sources?:string[]};if(!Array.isArray(result?.slides)||result.slides.length!==5)throw new Error("A geração não retornou os cinco slides completos.");const next:CarouselEngineContent={topic:topic.trim(),niche,tone,slides:result.slides,caption:result.caption||"",sources:result.sources||research.brief.fontes?.map(f=>f.url).filter(Boolean) as string[],research};setContent(next);setEditing(false);await scoreContent(next);}catch(e){toast.error(e instanceof Error?e.message:"Não consegui gerar o carrossel.");}finally{setLoading(false);}};
 const regenerate=async(index:number)=>{if(!content)return;setRegenerating(index);try{const {data,error}=await supabase.functions.invoke("social-on-generate",{body:{mode:"carousel_engine",topic:content.topic,niche:content.niche,tone:content.tone,handle,pesquisa:content.research,regenerateSlide:index+1,baseline:json(content.slides[index])}});if(error)throw error;const slide=(data?.result?.slides?.[index]||data?.result?.slide) as CarouselEngineSlide|undefined;if(!slide)throw new Error("Não recebi a nova versão do slide.");setContent({...content,slides:content.slides.map((s,i)=>i===index?slide:s)});}catch(e){toast.error(e instanceof Error?e.message:"Não consegui refazer o slide.");}finally{setRegenerating(null);}};
 const saveHistory=async()=>{if(!content)return;try{const u=await getUser();const {error}=await (supabase as any).from("social_carousel_history").insert({coach_id:u.id,topic:content.topic,niche:content.niche,tone:content.tone,slides:content.slides,caption:content.caption||null,sources:content.sources||[],score:score||content.score||null});if(error)throw error;toast.success("Carrossel salvo no histórico.");void loadHistory();}catch(e){toast.error(e instanceof Error?e.message:"Não consegui salvar.");}};
 const addPlanner=async()=>{if(!content)return;try{const u=await getUser();const {error}=await supabase.from("social_content_calendar").insert({coach_id:u.id,date:new Date().toISOString().slice(0,10),pillar:"mce_drop",format:"carrossel",topic:content.topic,hook:content.slides[0].type==="cover"?content.slides[0].title:content.topic,caption:content.caption||null,hashtags:[],status:"ready",source:"carousel_engine"} as any);if(error)throw error;toast.success("Adicionado ao Planner de hoje.");}catch(e){toast.error(e instanceof Error?e.message:"Não consegui adicionar ao Planner.");}};
 const downloadZip=async()=>{const z=new JSZip();for(let i=0;i<images.length;i++){const b=await(await fetch(images[i])).blob();z.file(`slide-${i+1}.png`,b);}const blob=await z.generateAsync({type:"blob"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="carrossel-cientifico.zip";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const openHistory=(r:CarouselHistoryRow)=>{setTopic(r.topic);setNiche(r.niche);setTone(r.tone);setScore(r.score);setContent({topic:r.topic,niche:r.niche,tone:r.tone,slides:r.slides,caption:r.caption||"",sources:r.sources||[],score:r.score});};
 const removeHistory=async(id:string)=>{await (supabase as any).from("social_carousel_history").delete().eq("id",id);setHistory(h=>h.filter(x=>x.id!==id));};
 return <div className="space-y-5"><CarouselInput topic={topic} niche={niche} tone={tone} loading={loading} onTopic={setTopic} onNiche={setNiche} onTone={setTone} onGenerate={()=>void generate()}/>{loading&&<div className="flex items-center justify-center gap-2 py-10 text-sm text-muted-foreground"><Loader2 className="animate-spin"/>Consultando fontes e diagramando...</div>}{content&&images.length===5&&<><CarouselPreview images={images} regenerating={regenerating} onEdit={()=>setEditing(v=>!v)} onRegenerate={(i)=>void regenerate(i)}/>{editing&&<SlideTextEditor content={content} onApply={setContent}/>}<CarouselScores score={score||content.score}/><div className="grid gap-2 sm:grid-cols-3"><Button variant="outline" className="rounded-none" onClick={()=>void saveHistory()}><Save/>Salvar histórico</Button><Button variant="outline" className="rounded-none" onClick={()=>void addPlanner()}><CalendarPlus/>Enviar ao Planner</Button><Button variant="outline" className="rounded-none" onClick={()=>void downloadZip()}>Baixar ZIP</Button></div><SaveShareButtons items={labels} labelSalvar="Salvar os 5 slides no álbum" texto={content.caption||content.topic}/>{content.caption&&<div className="border border-white/10 p-4"><p className="font-tech text-[10px] text-[#B8922A]">LEGENDA</p><textarea className="mt-2 min-h-36 w-full bg-transparent text-sm outline-none" value={content.caption} onChange={e=>setContent({...content,caption:e.target.value})}/></div>}</>}<CarouselHistory rows={history} onOpen={openHistory} onDelete={(id)=>void removeHistory(id)}/></div>;
}
