// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.2";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "N\xE3o autenticado." }],
    isError: true
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Obter perfil nutricional",
  description: "Retorna o perfil do usu\xE1rio autenticado: objetivo, peso, altura, metas de calorias e macros, n\xEDvel de treino e plano atual.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("profiles").select(
      "full_name, sex, date_of_birth, weight_kg, height_cm, meta_peso, goal, objetivo_principal, activity_level, nivel_treino, training_frequency, sport, dietary_restrictions, health_conditions, geb_kcal, get_kcal, vet_kcal, protein_g, carbs_g, fat_g, plano_atual, streak_days, level, xp"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail("Perfil n\xE3o encontrado para este usu\xE1rio.");
    return ok(data);
  }
});

// src/lib/mcp/tools/list-meal-logs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_meal_logs_default = defineTool2({
  name: "list_meal_logs",
  title: "Listar refei\xE7\xF5es registradas",
  description: "Lista as refei\xE7\xF5es registradas pelo usu\xE1rio autenticado, com calorias e macros, opcionalmente filtradas por intervalo de datas.",
  inputSchema: {
    from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data inicial (YYYY-MM-DD)."),
    to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Data final (YYYY-MM-DD)."),
    limit: z.number().int().min(1).max(100).default(30).describe("M\xE1ximo de registros.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("meal_logs").select(
      "id, meal_date, meal_type, total_kcal, total_protein, total_carbs, total_fat, food_names, quality_score, confirmed, notes"
    ).eq("user_id", ctx.getUserId()).order("meal_date", { ascending: false }).limit(limit ?? 30);
    if (from) query = query.gte("meal_date", from);
    if (to) query = query.lte("meal_date", to);
    const { data, error } = await query;
    if (error) return fail(error.message);
    return ok({ meals: data ?? [] });
  }
});

// src/lib/mcp/tools/log-weight.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var log_weight_default = defineTool3({
  name: "log_weight",
  title: "Registrar peso corporal",
  description: "Registra um novo peso corporal (e opcionalmente percentual de gordura e massa muscular) para o usu\xE1rio autenticado.",
  inputSchema: {
    weight_kg: z2.number().min(20).max(400).describe("Peso em quilogramas."),
    body_fat_pct: z2.number().min(1).max(70).optional().describe("Percentual de gordura corporal."),
    muscle_mass_kg: z2.number().min(1).max(200).optional().describe("Massa muscular em kg.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ weight_kg, body_fat_pct, muscle_mass_kg }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("weight_logs").insert({
      user_id: ctx.getUserId(),
      weight_kg,
      body_fat_pct: body_fat_pct ?? null,
      muscle_mass_kg: muscle_mass_kg ?? null
    }).select("id, weight_kg, body_fat_pct, muscle_mass_kg, logged_at").maybeSingle();
    if (error) return fail(error.message);
    return ok(data);
  }
});

// src/lib/mcp/tools/list-weight-logs.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_weight_logs_default = defineTool4({
  name: "list_weight_logs",
  title: "Hist\xF3rico de peso",
  description: "Retorna o hist\xF3rico de peso corporal do usu\xE1rio autenticado, do mais recente para o mais antigo.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).default(30).describe("M\xE1ximo de registros.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("weight_logs").select("id, weight_kg, body_fat_pct, muscle_mass_kg, logged_at").eq("user_id", ctx.getUserId()).order("logged_at", { ascending: false }).limit(limit ?? 30);
    if (error) return fail(error.message);
    return ok({ logs: data ?? [] });
  }
});

// src/lib/mcp/tools/list-training-protocols.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_training_protocols_default = defineTool5({
  name: "list_training_protocols",
  title: "Listar protocolos de treino",
  description: "Lista os protocolos de treino (TrainingON) do usu\xE1rio autenticado, com fase, n\xEDvel, m\xFAsculos e dura\xE7\xE3o.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).default(10).describe("M\xE1ximo de protocolos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("training_protocols").select(
      "id, client_name, phase, level, muscles, weeks, days_per_week, session_duration, equipment, injuries, created_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return fail(error.message);
    return ok({ protocols: data ?? [] });
  }
});

// src/lib/mcp/tools/get-training-protocol.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var get_training_protocol_default = defineTool6({
  name: "get_training_protocol",
  title: "Obter protocolo de treino",
  description: "Retorna o conte\xFAdo completo de um protocolo de treino do usu\xE1rio autenticado a partir do seu id.",
  inputSchema: {
    protocol_id: z5.string().uuid().describe("Id do protocolo (use list_training_protocols).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ protocol_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("training_protocols").select("*").eq("user_id", ctx.getUserId()).eq("id", protocol_id).maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail("Protocolo n\xE3o encontrado.");
    return ok(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "hibohvntewqtthyuotye";
var mcp_default = defineMcp({
  name: "nutrion-mcp",
  title: "nutriON",
  version: "0.1.0",
  instructions: "Ferramentas do nutriON para o usu\xE1rio autenticado: leitura do perfil nutricional e metas, hist\xF3rico de refei\xE7\xF5es e de peso, registro de novo peso e consulta dos protocolos de treino (TrainingON). N\xE3o prescreve medicamentos nem substitui avalia\xE7\xE3o cl\xEDnica.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    list_meal_logs_default,
    list_weight_logs_default,
    log_weight_default,
    list_training_protocols_default,
    get_training_protocol_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
