INSERT INTO public.mce_audio_episodes (series, episode_number, title, description, duration_seconds, scientific_reference, sort_order)
SELECT v.series, v.episode_number, v.title, v.description, v.duration_seconds, v.scientific_reference, v.sort_order
FROM (VALUES
('alter_ego',1,'Criando seu Alter Ego','Sessão guiada: nome, fisiologia e gatilho de ativação da sua versão imbatível.',1200,'Todd Herman · Amy Cuddy, Harvard',5000),
('alter_ego',2,'Ativação rápida do Alter Ego','3 minutos: postura de poder, nome em voz alta e a chave vira.',180,'Embodied cognition',5001),
('capsula',1,'Dia 1 — Grave sua cápsula','Mensagem para o eu de 30 dias: como se sente, o que teme, o que promete.',180,NULL,5002),
('capsula',2,'Dia 30 — Desbloqueio','Ouça a própria voz de 30 dias atrás e compare com os números de hoje.',300,NULL,5003),
('capsula',3,'Dia 90 — Desbloqueio','Três meses depois: a prova sonora da transformação.',300,NULL,5004),
('capsula',4,'Dia 365 — Desbloqueio','Um ano. A prova mais poderosa de transformação que existe.',360,NULL,5005),
('pre_refeicao',1,'Consciência','Olhe para o prato. Não é comida — é engenharia biológica.',60,NULL,5006),
('pre_refeicao',2,'Gratidão biológica','37 trilhões de células esperando o material de construção.',60,NULL,5007),
('pre_refeicao',3,'Intenção','Atletas não comem por prazer. Comem por projeto.',60,NULL,5008),
('pre_refeicao',4,'Desaceleração','O hipotálamo leva 20 minutos para registrar saciedade.',60,'Saciedade hipotalâmica',5009),
('pre_refeicao',5,'Farmacologia','Cúrcuma, pimenta-preta e NRF2: o prato como farmácia.',60,NULL,5010),
('pre_refeicao',6,'Identidade','Cada garfada é um voto na identidade que você constrói.',60,'James Clear',5011),
('pre_refeicao',7,'Corpo como templo','Você não coloca diesel num carro de fórmula 1.',60,NULL,5012),
('pre_refeicao',8,'Pós-treino GLUT-4','Os portões estão abertos. Essa é a janela. Sem culpa.',60,'GLUT-4 translocation',5013),
('periodizacao',1,'Bulking · Despertar','Superávit é investimento. Cada caloria é tijolo.',300,NULL,5014),
('periodizacao',2,'Bulking · Pré-refeição','Come tudo. Sem culpa. O corpo está em modo construção.',240,NULL,5015),
('periodizacao',3,'Bulking · Pré-treino','Energia sobrando é permissão para puxar mais carga.',240,NULL,5016),
('periodizacao',4,'Bulking · Pré-sono','Paciência: ganho de gordura temporário faz parte da obra.',300,NULL,5017),
('periodizacao',5,'Cutting · Despertar','O desconforto é temporário. O resultado é permanente.',300,NULL,5018),
('periodizacao',6,'Cutting · Pré-refeição','Cada caloria aqui é cirúrgica. Zero desperdício.',240,NULL,5019),
('periodizacao',7,'Cutting · Fome e irritabilidade','Gestão da fome e da resistência social no déficit.',360,NULL,5020),
('periodizacao',8,'Cutting · Pré-sono','A lipólise é mais ativa no sono. Dorme secando.',300,NULL,5021),
('periodizacao',9,'Recomposição · Despertar','Paciência extrema: a balança mente, o espelho conta.',300,NULL,5022),
('periodizacao',10,'Recomposição · Confiança no processo','Micro-progressos invisíveis somam meses de mudança.',300,NULL,5023),
('periodizacao',11,'Recomposição · Pré-treino','Estímulo alto com energia moderada: técnica acima de ego.',240,NULL,5024),
('periodizacao',12,'Recomposição · Pré-sono','Recuperação é onde a recomposição realmente acontece.',300,NULL,5025),
('periodizacao',13,'Peak Week · Controle','Cirúrgico. Cada grama importa. Zero improviso.',300,NULL,5026),
('periodizacao',14,'Peak Week · Ansiedade','Reduzir ruído mental na reta final.',300,NULL,5027),
('periodizacao',15,'Peak Week · Véspera','Protocolo militar: sono, água, carbo, cabeça fria.',300,NULL,5028),
('periodizacao',16,'Peak Week · Não sabotar','O erro clássico da última semana e como evitá-lo.',240,NULL,5029),
('periodizacao',17,'Deload · Permissão','Descanso é construção, não preguiça.',300,NULL,5030),
('periodizacao',18,'Deload · Restauração','Sistema nervoso central: por que ele precisa da semana leve.',300,NULL,5031),
('periodizacao',19,'Deload · Culpa zero','Treinar leve com inteligência é decisão de atleta.',240,NULL,5032),
('periodizacao',20,'Deload · Retomada','Como voltar da semana leve mais forte do que entrou.',300,NULL,5033),
('body_scan',1,'Gratidão corporal','12 minutos percorrendo o corpo — não para criticar, para agradecer.',720,NULL,5034),
('body_scan',2,'Reconexão pós-treino','Body scan curto para reconhecer o que o corpo acabou de fazer.',480,NULL,5035),
('desafio_mental',1,'Semana 1 — Silêncio matinal','10 minutos em silêncio total ao acordar. Treinar o córtex a tolerar o vazio.',180,NULL,5036),
('desafio_mental',2,'Semana 2 — Desconforto voluntário','1 banho gelado por dia, 30 segundos. Pré-frontal vencendo a amígdala.',180,NULL,5037),
('desafio_mental',3,'Semana 3 — Gratidão ativa','Uma mensagem real de gratidão por noite.',180,'Seligman',5038),
('desafio_mental',4,'Semana 4 — Refeição em silêncio','Uma refeição por dia sem tela: percepção interoceptiva.',180,NULL,5039),
('desafio_mental',5,'Semana 5 — Dizer não','Um não por dia. O exercício de força mais importante que existe.',180,NULL,5040),
('desafio_mental',6,'Semana 6 — Ensinar','Explique o MCE para alguém. Ensinar consolida.',180,'Feynman',5041),
('modo_guerra',1,'Modo Guerra — Padrão','90 segundos de ativação simpática antes da série pesada.',90,NULL,5042),
('modo_guerra',2,'Modo Guerra — Cardio / HIIT','Ativação para sessões metabólicas de alta intensidade.',90,NULL,5043),
('modo_guerra',3,'Modo Guerra — Tentação','Ativação de emergência para o momento em que você quase cede.',90,NULL,5044),
('subliminar',1,'Foco Total · 4h','14 Hz beta contínuo para trabalho e estudo. Sem voz.',14400,NULL,5045),
('subliminar',2,'Recuperação Profunda · 8h','2–4 Hz delta a noite inteira. Sono profundo e GH.',28800,NULL,5046),
('subliminar',3,'Criatividade · 3h','7–8 Hz theta/alpha — o estado das melhores ideias.',10800,NULL,5047),
('subliminar',4,'Calma Ativa · 2h','10 Hz alpha para estresse sem sedar.',7200,NULL,5048),
('hall_fama',1,'90 dias — Obsidiana em formação','Áudio de marco: três meses de consistência real.',240,NULL,5049),
('hall_fama',2,'180 dias — Meio ano','Áudio exclusivo com seus números reais. Você é outra pessoa biologicamente.',300,'Merzenich',5050),
('hall_fama',3,'365 dias — Um ano de MCE','O legado sonoro de quem sustentou um ano inteiro.',360,NULL,5051),
('hall_fama',4,'Academy completa','Todos os módulos concluídos. O áudio que só quem terminou tem.',300,NULL,5052)) AS v(series, episode_number, title, description, duration_seconds, scientific_reference, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.mce_audio_episodes e WHERE e.series = v.series AND e.episode_number = v.episode_number);