
ALTER TABLE public.fitoterapicos_lib
  ADD COLUMN IF NOT EXISTS nome_cientifico text,
  ADD COLUMN IF NOT EXISTS categorias text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS nota_elite text,
  ADD COLUMN IF NOT EXISTS nivel text DEFAULT 'intermediario',
  ADD COLUMN IF NOT EXISTS evidencia text DEFAULT 'moderada';

INSERT INTO public.fitoterapicos_lib
(nome, nome_cientifico, origem, categorias, mecanismo, dose, timing, ciclo, farmacocinetica, indicacoes, contraindicoes, interacoes, nota_elite, nivel, evidencia) VALUES

('Turkesterona', 'Ajuga turkestanica', 'Uzbequistão', ARRAY['Elite Performance','Hormonal & Reprodutivo'],
 'Agonista do receptor estrogênico β, síntese proteica via mTOR independente de androgênios, recuperação acelerada e ganho de massa magra natural.',
 '500-1000mg/dia', 'Com refeição (sensível à gordura)', '8-12 semanas on / 4 semanas off',
 '{"absorcao":"2-4h","atividade":"8-12h","meia_vida":"~4h","pico":"2-4h"}'::jsonb,
 ARRAY['Hipertrofia natural','Recuperação muscular','Síntese proteica','Suporte em TRT baixo'],
 ARRAY['Gravidez','Lactação','Câncer hormônio-dependente'],
 ARRAY['Potencializa: Leucina 3g pós-treino, Ecdisterona','Inibido por: jejum prolongado (precisa de gordura)','Antagoniza: nenhuma relevante documentada'],
 'Ben Pakulski e atletas do Team Elite usam 1g/dia em ciclos de 8 semanas. Melhor resposta em atletas naturais ou em TRT baixo. Combinar com leucina 3g pós-treino para máxima ativação de mTOR.',
 'elite','emergente'),

('Ecdisterona (Beta-Ecdisterona 95%)', 'Cyanotis vaga / Spinacia oleracea', 'Ásia Central / Europa', ARRAY['Elite Performance','Composição Corporal'],
 'Agonista ERβ, síntese proteica anabólica sem ação androgênica, melhora composição corporal e força.',
 '100-500mg/dia (padronizado 95%)', 'Com refeição principal', 'Contínuo ou 8 semanas',
 '{"absorcao":"1-3h","atividade":"6-10h","meia_vida":"~9h","pico":"2-3h"}'::jsonb,
 ARRAY['Hipertrofia natural','Recomposição corporal','Performance'],
 ARRAY['Gravidez','Lactação'],
 ARRAY['Potencializa: Turkesterona, whey protein','Inibido por: nenhuma relevante','Antagoniza: nenhuma relevante'],
 'Estudo de Isenmann 2019 mostrou ganhos comparáveis a SARMs. Coaches alemães de atletismo usam há décadas. Combinação sinérgica com Turkesterona para máximo efeito anabólico natural.',
 'elite','moderada'),

('Astaxantina', 'Haematococcus pluvialis', 'Microalga marinha', ARRAY['Elite Performance','Inflamação & Dor','Circulação & Microcirculação'],
 'Antioxidante mitocondrial 6000x mais potente que vitamina C; reduz dano oxidativo muscular, melhora recuperação e performance aeróbica, anti-inflamatório potente.',
 '8-12mg/dia', 'Com refeição gordurosa', 'Contínuo',
 '{"absorcao":"6-8h","atividade":"24h","meia_vida":"~16h","pico":"6-8h"}'::jsonb,
 ARRAY['Proteção mitocondrial','Recuperação muscular','Performance aeróbica','Saúde cardiovascular','Proteção em uso de AAS'],
 ARRAY['Alergia a algas'],
 ARRAY['Potencializa: Omega-3, CoQ10, vitamina E','Inibido por: refeição sem gordura','Antagoniza: nenhuma relevante'],
 'Stan Efferding recomenda 12mg/dia para todos os atletas de força e fisiculturismo. Proteção mitocondrial real durante uso de compostos androgênicos.',
 'elite','forte'),

('Spermidina', 'Triticum aestivum (germe) / Bacillus subtilis (natto)', 'Trigo germinado, natto, cogumelos', ARRAY['Elite Performance','Longevidade'],
 'Indutor de autofagia, renovação celular, proteção cardiovascular e neuroproteção; mimetizador de restrição calórica.',
 '1-2mg/dia (natural) ou 5-10mg/dia (extrato)', 'Manhã em jejum', 'Contínuo (longevidade)',
 '{"absorcao":"1-2h","atividade":"12-24h","meia_vida":"~6h","pico":"1-2h"}'::jsonb,
 ARRAY['Longevidade','Autofagia','Proteção cardiovascular','Neuroproteção','Atletas masters >35 anos'],
 ARRAY['Gravidez','Lactação'],
 ARRAY['Potencializa: jejum intermitente, resveratrol, NMN','Inibido por: alta ingestão proteica concomitante','Antagoniza: nenhuma relevante'],
 'Protocolo de longevidade de David Sinclair e Peter Attia. Coaches de longevidade como Rhonda Patrick recomendam para atletas masters acima de 35 anos.',
 'elite','emergente'),

('Fisetin', 'Cotinus coggygria', 'Morango, maçã, cebola', ARRAY['Elite Performance','Longevidade'],
 'Senolítico — elimina células senescentes; ativador SIRT1/AMPK, neuroprotetor potente, anti-aging.',
 '100-500mg/dia em pulso (2-3 dias/mês)', 'Com refeição gordurosa', 'Pulso mensal 2-3 dias consecutivos',
 '{"absorcao":"2-4h","atividade":"24-48h","meia_vida":"~3-5h","pico":"2-3h"}'::jsonb,
 ARRAY['Senólise','Longevidade','Atletas masters com histórico de lesão','Neuroproteção'],
 ARRAY['Gravidez','Uso de imunossupressores','Quimioterapia ativa'],
 ARRAY['Potencializa: Quercetina (stack senolítico), Dasatinibe','Inibido por: refeição sem gordura','Antagoniza: nenhuma relevante'],
 'Protocolo senolítico de Mayo Clinic. Coaches de longevidade usam junto com Quercetina para limpeza de células zumbi. Atletas masters com histórico de lesão respondem muito bem.',
 'elite','emergente'),

('Quercetina Fitossomada (Quercefit)', 'Sophora japonica', 'Maçã, cebola, alcaparra', ARRAY['Elite Performance','Imunidade & Antimicrobianos','Inflamação & Dor'],
 'Senolítico, inibidor JAK, anti-inflamatório, antioxidante; ionóforo de zinco (análogo à HCQ); melhora biodisponibilidade de zinco.',
 '500-1000mg/dia (fitossomada)', 'Com refeição', 'Contínuo ou pulso mensal',
 '{"absorcao":"1-2h","atividade":"8-12h","meia_vida":"~11h","pico":"1-3h"}'::jsonb,
 ARRAY['Longevidade','Imunomodulação','Anti-inflamatório','Suporte cardiovascular'],
 ARRAY['Doença renal grave','Anticoagulantes (cautela)'],
 ARRAY['Potencializa: Zinco, Bromelina, Fisetin','Inibido por: chá preto (taninos), café em altas doses','Antagoniza: ciclosporina'],
 'Peter Attia usa 500mg/dia como base de longevidade. Combinação clássica Quercetina + Zinco + Bromelina para máxima absorção e efeito imunomodulador.',
 'elite','moderada'),

('Tongkat Ali (Physta® 200:1)', 'Eurycoma longifolia', 'Malásia / Indonésia', ARRAY['Elite Hormonal','Hormonal & Reprodutivo','Performance & Energia'],
 'Inibidor de SHBG — libera testosterona livre; estimula células de Leydig, reduz cortisol; adaptógeno androgênico.',
 '200-400mg/dia (extrato 200:1)', 'Manhã, com ou sem refeição', '5 dias on / 2 dias off',
 '{"absorcao":"1-2h","atividade":"8-12h","meia_vida":"~6h","pico":"1-2h"}'::jsonb,
 ARRAY['TRT suporte natural','Otimização hormonal','Redução de cortisol','Libido'],
 ARRAY['Câncer de próstata','Hipertensão não controlada','Uso de imunossupressores'],
 ARRAY['Potencializa: Ashwagandha KSM-66, zinco','Inibido por: estresse crônico não controlado','Antagoniza: imunossupressores'],
 'Padrão ouro para suporte TRT natural. Coaches de MMA e fisiculturismo natural usam 400mg Physta® (extrato padronizado MIT). Combinar com Ashwagandha KSM-66 para máximo suporte ao eixo HPT.',
 'elite','moderada'),

('Fadogia Agrestis', 'Fadogia agrestis', 'Nigéria', ARRAY['Elite Hormonal','Hormonal & Reprodutivo'],
 'Estimula LH endógeno, aumenta testosterona total; afrodisíaco e adaptógeno.',
 '300-600mg/dia', 'Manhã', '8 semanas on / 4 semanas off',
 '{"absorcao":"1-3h","atividade":"8-12h","meia_vida":"~5h","pico":"2h"}'::jsonb,
 ARRAY['Estímulo de LH','PCT pós-ciclo','Libido','TRT otimizado'],
 ARRAY['Hepatopatias','Uso de hepatotóxicos','Doses >600mg sem monitoramento'],
 ARRAY['Potencializa: Tongkat Ali, zinco','Inibido por: álcool','Antagoniza: nenhuma relevante'],
 'Andrew Huberman popularizou. Coaches de TRT otimizado usam durante o PCT para estimular recuperação testicular. Atenção: hepatotóxico em doses altas — monitorar enzimas hepáticas.',
 'elite','emergente'),

('Mucuna Pruriens (L-DOPA 15%)', 'Mucuna pruriens', 'Índia (feijão-veludo)', ARRAY['Elite Hormonal','Hormonal & Reprodutivo','Cognição & Neuroproteção'],
 'Precursor de dopamina; estimula GH endógeno via dopamina; aumenta testosterona, reduz prolactina; neuroprotetor.',
 '300-500mg/dia (15% L-DOPA)', 'Noite (estimula GH noturno)', 'Ciclado 5 on / 2 off',
 '{"absorcao":"1-2h","atividade":"6-8h","meia_vida":"~1-2h","pico":"1h"}'::jsonb,
 ARRAY['Controle de prolactina','GH endógeno noturno','Neuroproteção','Libido'],
 ARRAY['Parkinson em tratamento','Psicose','Uso de IMAO'],
 ARRAY['Potencializa: Ipamorelin, vitamina B6','Inibido por: proteína em altas doses concomitante','Antagoniza: antipsicóticos'],
 'Combinação clássica com Ipamorelin para potencializar GH endógeno. Coaches de anti-aging usam para controle de prolactina em atletas usando NPP ou Tren.',
 'elite','moderada'),

('Lions Mane (Hericenona >= 1%)', 'Hericium erinaceus', 'Ásia (fungo)', ARRAY['Elite Cognitivo','Cognição & Neuroproteção'],
 'Estimula NGF (Nerve Growth Factor); neuroplasticidade, remielinização, neuroproteção, memória e foco.',
 '500-1000mg/dia (extrato dual água+álcool)', 'Manhã com café', 'Contínuo (efeitos cumulativos)',
 '{"absorcao":"2-4h","atividade":"8-12h","meia_vida":"~6h","pico":"2-3h"}'::jsonb,
 ARRAY['Foco cognitivo','Memória','Neuroplasticidade','Remielinização'],
 ARRAY['Alergia a fungos'],
 ARRAY['Potencializa: L-Teanina, Cafeína, Niacina','Inibido por: extrato de baixa qualidade (sem hericenonas)','Antagoniza: nenhuma relevante'],
 'Paul Stamets (Fungi Perfecti) e coaches de neurohacking recomendam stack Lions Mane + Niacina. Para atletas: Lions Mane + L-Teanina + Cafeína = foco de elite sem crash.',
 'elite','moderada'),

('Noopept (GVS-111)', 'N-fenilacetil-L-prolilglicina etil éster', 'Rússia (nootrópico peptídico)', ARRAY['Elite Cognitivo','Experimental','Cognição & Neuroproteção'],
 'Pró-fármaco de cicloprolilglicina; potencia AMPA e NMDA, aumenta NGF e BDNF, neuroproteção, memória de trabalho.',
 '10-30mg/dia', 'Manhã ou pré-treino cognitivo', '56 dias on / 4 semanas off',
 '{"absorcao":"15-30min (sublingual)","atividade":"4-6h","meia_vida":"~30-60min (metabolitos ativos)","pico":"15-30min"}'::jsonb,
 ARRAY['Performance cognitiva','Memória de trabalho','Neuroproteção'],
 ARRAY['Gravidez','Lactação','Crises epilépticas','Menores de 18 anos'],
 ARRAY['Potencializa: Alpha-GPC, Bacopa monnieri','Inibido por: álcool','Antagoniza: nenhuma relevante'],
 'Coaches russos e búlgaros usam desde os anos 90 com atletas de força. Stack Noopept + Alpha-GPC + Bacopa = performance cognitiva de elite. Sublingual para onset mais rápido.',
 'experimental','emergente'),

('Alpha-GPC', 'L-Alfa Glicerilfosforilcolina', 'Sintetizado (precursor de colina)', ARRAY['Elite Cognitivo','Performance & Energia','Hormonal & Reprodutivo'],
 'Precursor de acetilcolina; estimula GH (600mg dose única); melhora força e potência muscular; nootrópico colinérgico.',
 '300-600mg/dia (600mg pré-treino para pico GH)', '30-60min pré-treino', 'Contínuo',
 '{"absorcao":"30-60min","atividade":"4-6h","meia_vida":"~4h","pico":"60-90min"}'::jsonb,
 ARRAY['Pico de GH pré-treino','Força e potência','Foco cognitivo'],
 ARRAY['Depressão bipolar','Hipotensão grave'],
 ARRAY['Potencializa: GABA, Mucuna Pruriens (à noite)','Inibido por: anticolinérgicos','Antagoniza: anticolinérgicos'],
 'Ben Pakulski recomenda 600mg Alpha-GPC + 300mg GABA pré-treino para maximizar pico de GH natural. Stack com Mucuna Pruriens à noite para GH noturno otimizado.',
 'elite','forte'),

('Betaína Anidra (Trimetilglicina)', 'Betaina anidra', 'Beterraba / sintetizada', ARRAY['Elite Recuperação','Performance & Energia'],
 'Doadora de metil; aumenta creatina endógena, síntese proteica, potência e força; reduz homocisteína.',
 '2.5-5g/dia (dividido pré e pós-treino)', 'Pré e pós-treino dividido', 'Contínuo',
 '{"absorcao":"1-2h","atividade":"6-12h","meia_vida":"~14h","pico":"1h"}'::jsonb,
 ARRAY['Força e potência','Síntese de creatina endógena','Recuperação','Composição corporal'],
 ARRAY['Doença renal grave'],
 ARRAY['Potencializa: Creatina monohidratada, B12, B6','Inibido por: nenhuma relevante','Antagoniza: nenhuma relevante'],
 'Stan Efferding (VERTICAL DIET) usa betaina em todos seus atletas de powerlifting e fisiculturismo. 2.5g pré + 2.5g pós = protocolo padrão.',
 'elite','forte'),

('Ashwagandha Sensoril (Raiz + Folha 10% withanolídeos)', 'Withania somnifera', 'Índia', ARRAY['Elite Recuperação','Hormonal & Reprodutivo','Performance & Energia'],
 'Adaptógeno com maior concentração de withanolídeos (10% vs 5% KSM-66); maior redução de cortisol, melhor para recuperação e estresse.',
 '125-250mg/dia (Sensoril)', 'Noite (redução de cortisol)', 'Contínuo',
 '{"absorcao":"1-2h","atividade":"12-24h","meia_vida":"~6-7h","pico":"2h"}'::jsonb,
 ARRAY['Overtraining','Cutting agressivo','Redução de cortisol','Sono e recuperação'],
 ARRAY['Hipertireoidismo','Gravidez','Uso de imunossupressores','Doença autoimune ativa'],
 ARRAY['Potencializa: Magnésio bisglicinato, L-Teanina','Inibido por: cafeína em altas doses à noite','Antagoniza: imunossupressores, hormônios tireoidianos'],
 'Para atletas com overtraining ou em cutting agressivo, Sensoril é superior ao KSM-66 para cortisol. Para testosterona e força, KSM-66 tem edge. Coaches de elite usam os dois em fases diferentes.',
 'elite','forte'),

('Bergamot BPF (Polifenóis de Bergamota)', 'Citrus bergamia', 'Calábria (Itália)', ARRAY['Elite Cardiovascular','Colesterol & Cardiovascular'],
 'Inibidor PCSK9 natural; aumenta HDL dramaticamente, reduz LDL oxidado, melhora sensibilidade insulínica; efeito estatina-like sem miotoxicidade.',
 '500-1000mg/dia (BPF padronizado)', 'Com refeição principal', 'Contínuo (monitorar lipídios)',
 '{"absorcao":"1-3h","atividade":"12-24h","meia_vida":"~8h","pico":"2-3h"}'::jsonb,
 ARRAY['Dislipidemia','Atletas em uso de AAS','Resistência insulínica','Proteção cardiovascular'],
 ARRAY['Hipotensão grave','Alergia a cítricos'],
 ARRAY['Potencializa: CoQ10, Ômega-3, Policosanol','Inibido por: nenhuma relevante','Antagoniza: nenhuma relevante'],
 'William Llewellyn recomenda para atletas usando AAS com dislipidemia. Coaches de farmacologia usam como proteção cardiovascular de base. Combinar com Coenzima Q10 e Ômega-3.',
 'elite','forte'),

('Espirulina + Clorela (Detox de Metais)', 'Arthrospira platensis + Chlorella vulgaris', 'Algas verde-azuladas', ARRAY['Elite Cardiovascular','Hepatoproteção & Detox','Imunidade & Antimicrobianos'],
 'Clorela quelante de metais pesados; espirulina rica em ficocianina antioxidante; proteína completa; detox hepático e renal.',
 'Espirulina 3-10g/dia + Clorela 3-5g/dia', 'Pré-refeição (quelação)', '4-8 semanas on / 4 off',
 '{"absorcao":"1-3h","atividade":"6-12h","meia_vida":"~variável","pico":"2-4h"}'::jsonb,
 ARRAY['Detox de metais pesados','Suporte hepático','Suporte renal','Antioxidante geral'],
 ARRAY['Doenças autoimunes ativas','Fenilcetonúria','Hipertireoidismo (iodo na espirulina)'],
 ARRAY['Potencializa: Glutationa, NAC, Selênio','Inibido por: refeições muito gordurosas (quelação)','Antagoniza: imunossupressores'],
 'Protocolo de detox de heavy metals usado por coaches de longevidade. Essencial em atletas com exposição a metais (suplementos de baixa qualidade, ambiente industrial).',
 'elite','moderada'),

('DIM (3,3-Diindolilmetano)', '3,3-Diindolilmetano', 'Brócolis / crucíferos (extrato)', ARRAY['Elite Feminino','Hormonal & Reprodutivo'],
 'Modulador estrogênico; converte estrogênios ruins (16α-OHE1) em bons (2-OHE1); anti-aromatase parcial; proteção mamária.',
 '100-200mg/dia', 'Com refeição gordurosa', 'Contínuo em atletas femininas',
 '{"absorcao":"2-4h","atividade":"12-24h","meia_vida":"~10h","pico":"3-4h"}'::jsonb,
 ARRAY['Retenção hídrica estrogênica','Atletas femininas em prep','Modulação estrogênica','Saúde mamária'],
 ARRAY['Gravidez','Lactação','Câncer hormônio-dependente em tratamento'],
 ARRAY['Potencializa: Calcium D-Glucarate, I3C, Sulforafano','Inibido por: dieta extremamente low-fat','Antagoniza: reposição estrogênica'],
 'Chad Nicholls e coaches de bikini/wellness usam DIM em toda atleta feminina em prep. Controla retenção hídrica estrogênica sem secar demais. Combinar com Calcium D-Glucarate para detox estrogênico completo.',
 'elite','moderada'),

('Calcium D-Glucarate', 'D-Glucarato de cálcio', 'Maçã, brócolis, crucíferos', ARRAY['Elite Feminino','Hepatoproteção & Detox','Hormonal & Reprodutivo'],
 'Inibe beta-glucuronidase; aumenta excreção de estrogênios conjugados; suporta detox de fase II hepática.',
 '500-1500mg/dia', 'Com refeições', 'Contínuo',
 '{"absorcao":"1-2h","atividade":"8-12h","meia_vida":"~4-6h","pico":"2h"}'::jsonb,
 ARRAY['Detox estrogênico','Atletas femininas em competição','Saúde hepática fase II'],
 ARRAY['Hipercalcemia','Hiperparatireoidismo'],
 ARRAY['Potencializa: DIM, I3C, Sulforafano','Inibido por: nenhuma relevante','Antagoniza: medicamentos metabolizados via glucuronidação (consultar)'],
 'Stack clássico de coaches femininos: DIM + Calcium D-Glucarate + I3C = controle estrogênico completo. Usado em toda atleta de competição feminina por coaches IFBB de elite.',
 'elite','moderada');
