ALTER TABLE public.apex_analyses
  ADD COLUMN IF NOT EXISTS protocol TEXT,
  ADD COLUMN IF NOT EXISTS cycle_goal TEXT,
  ADD COLUMN IF NOT EXISTS cycle_week INTEGER,
  ADD COLUMN IF NOT EXISTS cycle_duration INTEGER,
  ADD COLUMN IF NOT EXISTS support TEXT,
  ADD COLUMN IF NOT EXISTS tdee_factor NUMERIC,
  ADD COLUMN IF NOT EXISTS protein_ideal TEXT;