
CREATE TABLE IF NOT EXISTS public.athlete_exams (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID REFERENCES auth.users(id) NOT NULL,
  data_coleta       DATE NOT NULL,
  fase              TEXT,
  ciclo_atual       TEXT,
  semana_ciclo      INTEGER,
  testosterona_total   DECIMAL,
  testosterona_livre   DECIMAL,
  estradiol            DECIMAL,
  lh                   DECIMAL,
  fsh                  DECIMAL,
  shbg                 DECIMAL,
  prolactina           DECIMAL,
  dhea_s               DECIMAL,
  progesterona         DECIMAL,
  igf1                 DECIMAL,
  gh                   DECIMAL,
  cortisol_matinal     DECIMAL,
  tsh                  DECIMAL,
  t3_livre             DECIMAL,
  t4_livre             DECIMAL,
  ast_tgo              DECIMAL,
  alt_tgp              DECIMAL,
  ggt                  DECIMAL,
  fosfatase_alcalina   DECIMAL,
  bilirrubina_total    DECIMAL,
  bilirrubina_direta   DECIMAL,
  bilirrubina_indireta DECIMAL,
  colesterol_total     DECIMAL,
  ldl                  DECIMAL,
  hdl                  DECIMAL,
  triglicerideos       DECIMAL,
  pcr_ultrassensivel   DECIMAL,
  homocisteina         DECIMAL,
  pa_sistolica         INTEGER,
  pa_diastolica        INTEGER,
  hematocrito          DECIMAL,
  hemoglobina          DECIMAL,
  leucocitos           DECIMAL,
  plaquetas            DECIMAL,
  vhs                  DECIMAL,
  creatinina           DECIMAL,
  ureia                DECIMAL,
  acido_urico          DECIMAL,
  tfg_estimado         DECIMAL,
  microalbuminuria     DECIMAL,
  glicemia_jejum       DECIMAL,
  insulina_jejum       DECIMAL,
  hba1c                DECIMAL,
  homa_ir              DECIMAL,
  vitamina_d           DECIMAL,
  calcio               DECIMAL,
  fosforo              DECIMAL,
  magnesio             DECIMAL,
  ferro_serico         DECIMAL,
  ferritina            DECIMAL,
  b12                  DECIMAL,
  zinco                DECIMAL,
  psa                  DECIMAL,
  analise_ia           TEXT,
  alertas              TEXT[],
  acoes_prioritarias   JSONB,
  suplementacao_ajust  JSONB,
  proximos_exames      JSONB,
  semaforo_geral       TEXT,
  variacao_baseline    JSONB,
  tendencias           JSONB,
  notas_medico         TEXT,
  medicacoes_atuais    TEXT[],
  revisado_medico      BOOLEAN DEFAULT false,
  created_at           TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.cycle_tracking (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID REFERENCES auth.users(id) NOT NULL,
  nome_ciclo        TEXT,
  data_inicio       DATE,
  data_fim_prevista DATE,
  compostos         JSONB,
  doses             JSONB,
  protocolo_suporte JSONB,
  fase_atual        TEXT,
  semana_atual      INTEGER,
  tpc_protocolo     JSONB,
  observacoes       TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.exam_alerts (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID REFERENCES auth.users(id) NOT NULL,
  exam_id           UUID REFERENCES public.athlete_exams(id),
  nivel             TEXT,
  marcador          TEXT,
  valor             DECIMAL,
  mensagem          TEXT,
  acao_recomendada  TEXT,
  resolvido         BOOLEAN DEFAULT false,
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.athlete_exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cycle_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User exams" ON public.athlete_exams FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "User cycle" ON public.cycle_tracking FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "User alerts" ON public.exam_alerts FOR ALL USING (auth.uid() = user_id);
