
INSERT INTO public.fitoterapicos_lib (nome, origem, mecanismo, dose, timing, ciclo, indicacoes, contraindicoes, interacoes, farmacocinetica) VALUES

-- 1. BERBERINA
('Berberina', 'Coptis chinensis, Berberis vulgaris', 'Ativa AMPK (igual Metformina), inibe DPP-4, reduz produção hepática de glicose, melhora sensibilidade de receptor insulínico, modula microbioma positivamente', '500mg 3x/dia (antes das 3 principais refeições)', '15-20min ANTES da refeição', '8 semanas on / 4 semanas off', ARRAY['Resistência insulínica','Pré-diabetes','Síndrome metabólica','Triglicerídeos altos','Antimicrobiano intestinal'], ARRAY['Hipoglicemia com insulina exógena'], ARRAY['Potencializa hipoglicemiantes','Reduzir dose se usando Metformina','Antibióticos reduzem flora e eficácia'], '{"absorcao":"30-60min","meia_vida":"4-6h","biodisponibilidade":"5% oral mas efeito local intestinal potente + acúmulo tecidual","metabolismo":"hepático CYP3A4","combinacao_sinergica":"Berberina + Silimarina = absorção 60% maior"}'::jsonb),

-- 2. JIAOGULAN
('Gynostemma pentaphyllum (Jiaogulan)', 'Ásia — erva da imortalidade chinesa', 'Ativação AMPK mais potente que Berberina, ativação de SIRT1 (longevidade), anti-inflamatório via NF-κB, adaptógeno adrenal', '200-450mg extrato padronizado (gypenosídeos 98%) OU chá 3-5g folhas 2x/dia', 'Manhã em jejum + 30min antes do jantar', 'Uso contínuo (seguro para uso crônico)', ARRAY['Resistência insulínica severa','Síndrome metabólica','Triglicerídeos elevados (reduz até 22%)','Colesterol (reduz LDL, eleva HDL)','Fadiga adrenal'], ARRAY[]::text[], ARRAY['Jiaogulan + Berberina + Cromo = protocolo de sensibilidade insulínica máximo'], '{"absorcao":"45-90min","meia_vida":"6-8h","pico":"2h","eliminacao":"renal e biliar"}'::jsonb),

-- 3. AGRIMÔNIA
('Agrimônia (Agrimonia eupatoria)', 'Europa/Ásia — usada por coaches alemães e escandinavos', 'Inibe alfa-glicosidase (igual Acarbose), reduz pico glicêmico pós-prandial, estimula secreção de insulina dose-dependente, anti-inflamatório pancreático', '700mg extrato seco 3x/dia OU chá 2-3g em 200ml', 'IMEDIATAMENTE antes das refeições (mecanismo prandial)', 'Contínuo, seguro', ARRAY['Pré-diabetes','Glicemia pós-prandial alta','Resistência insulínica leve-moderada'], ARRAY[]::text[], ARRAY[]::text[], '{"absorcao":"30-45min","meia_vida":"4-5h","pico":"1-1.5h","metabolismo":"hepático"}'::jsonb),

-- 4. BANABA (Ácido Corosólico)
('Ácido Corosólico (Banaba / Lagerstroemia speciosa)', 'Filipinas/Ásia — usado por coaches japoneses e americanos de elite', 'Ativa receptor GLUT4 diretamente (mesmo alvo da insulina), inibe alfa-glicosidase, efeito insulinomimético', '10-48mg ácido corosólico/dia (extrato 18%)', '30min antes das refeições principais', 'Contínuo', ARRAY['Resistência insulínica','Glicemia pós-prandial','Composição corporal'], ARRAY['Hipoglicemia (cuidado com insulina)'], ARRAY['Banaba + Berberina + Gymnema = tríade insulínica'], '{"absorcao":"30-60min","meia_vida":"8-10h","pico":"2h","biodisponibilidade":"alta (lipofílico)","metabolismo":"hepático mínimo"}'::jsonb),

-- 5. GYMNEMA SYLVESTRE
('Gymnema Sylvestre', 'Índia — Ayurveda — destruidor do açúcar', 'Bloqueia receptores de doce na língua, estimula regeneração de células beta pancreáticas, aumenta secreção de insulina, reduz absorção de glicose intestinal', '200-400mg extrato (75% ácidos gimnêmicos) 2x/dia', '30min antes das refeições ricas em carb. Uso especial: 5min antes de cheat meal', '12-24 semanas com monitoramento', ARRAY['Compulsão por doce','Pré-diabetes','Hiperglicemia pós-prandial severa'], ARRAY[]::text[], ARRAY[]::text[], '{"absorcao":"45-60min","meia_vida":"6-8h","pico":"2-3h","eliminacao":"biliar predominante"}'::jsonb),

-- 6. INOSITOL
('Inositol (Myo-Inositol + D-Chiro-Inositol)', 'Segundo mensageiro da insulina', 'Amplifica sinalização pós-receptor insulínico, converte Myo em D-Chiro nos tecidos (enzima EPM) que ativa cascata de sinalização da insulina', 'Myo 2g + D-Chiro 250mg (ratio 8:1). SOP: 4g Myo + 400mg D-Chiro 2x/dia', 'Manhã em jejum + antes de dormir', 'Contínuo', ARRAY['SOP','Resistência insulínica','Ansiedade','Saúde ovariana','Qualidade de ovócitos'], ARRAY[]::text[], ARRAY['Myo-Inositol + Ácido Fólico 400mcg = sinergia comprovada'], '{"absorcao_myo":"30-45min","absorcao_dchiro":"60-90min","meia_vida":"6-8h","excrecao":"renal"}'::jsonb),

-- 7. AFRICAN MANGO
('African Mango (Irvingia gabonensis)', 'África Ocidental — usado por coaches americanos de elite', 'Inibe adipogênese, reduz leptina (sensibilidade), melhora adiponectina, reduz absorção de gordura via inibição de lipase, reduz glicemia pós-prandial', '150mg extrato padronizado 2x/dia', '30-60min ANTES das refeições principais', '10-12 semanas on / 4 semanas off', ARRAY['Gordura visceral','Leptina elevada','Adiponectina baixa','Composição corporal'], ARRAY[]::text[], ARRAY[]::text[], '{"absorcao":"60-90min","meia_vida":"8-12h","pico":"3h","eliminacao":"fecal predominante"}'::jsonb),

-- 8. KUDZU
('Kudzu (Pueraria lobata)', 'Ásia — usado por coaches japoneses', 'Isoflavonas (puerarina, daidzein) melhoram GLUT4, efeito estrogênico fraco, vasodilatador, reduz craving por álcool', '100-300mg extrato (40% puerarina) 2x/dia. Homens: < 200mg para evitar efeito estrogênico', 'Com refeições', 'Contínuo com dose controlada', ARRAY['Sensibilidade insulínica','Craving por álcool em off-season','Vasodilatação muscular'], ARRAY['Homens com sensibilidade estrogênica (manter dose baixa)'], ARRAY[]::text[], '{"absorcao":"45-60min","meia_vida":"6h","pico":"1.5-2h","metabolismo":"hepático (isoflavonas)"}'::jsonb),

-- 9. NATTOKINASE
('Nattokinase', 'Natto (soja fermentada japonesa)', 'Fibrinólise direta (dissolve coágulos), inibe PAI-1, reduz viscosidade sanguínea, reduz fibrinogênio, antitrombótico', '2000-4000 FU/dia dividido em 2 doses', 'Em jejum absoluto — NUNCA com refeição. Acordar + antes de dormir', 'Contínuo em usuários de AAS', ARRAY['Prevenção trombótica','Hematócrito alto','Viscosidade sanguínea','Aterosclerose'], ARRAY['Distúrbios hemorrágicos'], ARRAY['Potencializa anticoagulantes (Warfarina) — monitorar INR'], '{"absorcao":"30-60min","meia_vida":"8-12h","pico_fibrinolitico":"4-6h","atividade":"8-12h"}'::jsonb),

-- 10. SERRAPEPTASE
('Serrapeptase', 'Serratia marcescens (bactéria do bicho-da-seda) — Japão', 'Protease que dissolve tecido não-vivo, anti-inflamatório potente, reduz edema, dissolve aderências pós-cirúrgicas, limpa artérias de placa fibrinosa', '10-60mg (100.000-600.000 UI) 2-3x/dia. Revestimento entérico OBRIGATÓRIO', 'Jejum absoluto — 30min ANTES de alimento ou 2h APÓS', 'Contínuo conforme necessidade', ARRAY['Ateromas','Inflamação crônica','Sinusite','Edema','Fibrose'], ARRAY[]::text[], ARRAY['Nattokinase + Serrapeptase + Lumbrokinase = Fibrin Triad cardiovascular elite'], '{"absorcao":"entérica obrigatória","pico":"3-4h","meia_vida":"4-6h","atividade":"8-10h"}'::jsonb),

-- 11. LUMBROKINASE
('Lumbrokinase', 'Lumbricus rubellus (minhoca vermelha) — China/EUA', 'O mais potente dos enzimas fibrinolíticos, dissolve fibrina ativa E fibrinogênio, inibe agregação plaquetária, anti-aterosclerótico', '20mg 2x/dia (em jejum)', 'Acordar + antes de dormir (jejum)', '3 meses on / 1 mês off', ARRAY['Trombose','Aterosclerose','Hematócrito alto','Viscosidade sanguínea'], ARRAY['Não combinar com anticoagulantes sem supervisão'], ARRAY['Parte da Fibrin Triad com Nattokinase e Serrapeptase'], '{"absorcao":"entérica obrigatória","pico":"3-5h","meia_vida":"6-8h","estabilidade":"mais estável que Nattokinase em pH variável"}'::jsonb),

-- 12. PYCNOGENOL
('Pycnogenol (Casca de Pinheiro Marítimo)', 'Pinus pinaster — França/Portugal', 'Inibidor de fosfodiesterase (similar ao Viagra mas mais fraco — via NO), anti-inflamatório potente (COX-1 e COX-2), antioxidante (OPC), melhora microcirculação, vasodilatador', '100-200mg/dia (extrato 95% OPC)', 'Manhã com refeição (absorção com gordura)', 'Contínuo', ARRAY['Microcirculação','Disfunção erétil natural','Antioxidante','Pump pré-treino','Anti-inflamatório vascular'], ARRAY[]::text[], ARRAY['Pycnogenol 80mg + L-Arginina 3g = protocolo NO para DE (estudo ESCOP 2003)','Combinar com Vitamina C para regeneração'], '{"absorcao":"30-60min","meia_vida":"6-8h","pico":"2h","biodisponibilidade":"alta (procianidinas lipofílicas)"}'::jsonb),

-- 13. SCHISANDRA
('Schisandra chinensis', 'China/Rússia — adaptógeno hepático', 'Induz fase II de destoxificação hepática, hepatoprotetor (lignanas schisandrinas), adaptógeno adrenal, melhora VO2max, neuroprotetor, anti-inflamatório', '500mg-1g extrato (9% schisandrinas) 2x/dia', 'Manhã + tarde, com ou sem refeição', 'Contínuo durante uso de 17AA', ARRAY['Hepatoproteção','Destoxificação hepática','Fadiga adrenal','VO2max','Neuroproteção'], ARRAY[]::text[], ARRAY['Schisandra + TUDCA + NAC = protocolo hepático completo para orais 17AA'], '{"absorcao":"60-90min","meia_vida":"6-8h","pico":"2-3h","metabolismo":"hepático extenso"}'::jsonb),

-- 14. ANDROGRAPHIS
('Andrographis paniculata', 'Índia/Sri Lanka — Rei dos Amargos', 'Hepatoprotetor (andrografólida), imunomodulador, anti-inflamatório (NF-κB), antiviral, antiparasitário, colerético (fluxo biliar)', '400mg extrato (30% andrografólida) 2-3x/dia', 'Antes das refeições', '8-12 semanas máximo (uso prolongado pode suprimir imunidade)', ARRAY['Hepatoproteção','Imunidade','Infecções virais','Parasitas','Fluxo biliar'], ARRAY['Gravidez (abortivo)'], ARRAY[]::text[], '{"absorcao":"30-60min","meia_vida":"6-8h","pico":"1.5-2h","eliminacao":"biliar e renal"}'::jsonb),

-- 15. SILIMARINA FITOSSOMADA
('Silimarina Fitossomada (Siliphos)', 'Pinus pinaster / Silybum marianum', 'Hepatoprotetor de elite. Forma fitossomada (Siliphos) tem absorção 4-7x MAIOR que Silimarina padrão', 'Siliphos: 120-360mg 2x/dia OU Silimarina padrão: 400-600mg 3x/dia', 'SEMPRE com refeição contendo gordura (lipofílica)', 'Contínuo durante uso de hepatotóxicos', ARRAY['Hepatoproteção avançada','Uso de orais 17AA','Destoxificação','Fibrose hepática'], ARRAY[]::text[], ARRAY['Siliphos + TUDCA + Schisandra = protocolo hepático triplo de elite'], '{"absorcao_padrao":"23-47%","absorcao_fitossomada":"4-7x maior","meia_vida":"6-8h","pico":"2h"}'::jsonb),

-- 16. BOSWELLIA SERRATA
('Boswellia Serrata (AKBA > 30%)', 'Índia — Frankincense Elite', 'Inibe 5-LOX (leucotrienos — inflamação articular profunda), inibe MMP (degradação de cartilagem), anti-inflamatório mais específico para articulações que curcumina', '100-250mg AKBA/dia OU 800-1200mg extrato 37.5% AKBA 2x/dia', 'Com refeição gordurosa (absorção crítica)', 'Contínuo para inflamação articular', ARRAY['Artrite','Inflamação articular','Dor crônica','Proteção de cartilagem'], ARRAY[]::text[], ARRAY['Boswellia + Curcumina + Colágeno tipo II = protocolo articular elite','Versão com piperina: absorção 60% maior'], '{"absorcao":"60-90min","meia_vida":"6-8h","pico":"3h","nota":"lipofílica — tomar com gordura"}'::jsonb),

-- 17. UNHA DE GATO
('Uncaria tomentosa (Unha de Gato / Cat''s Claw)', 'Amazônia — subestimada no Brasil', 'Imunomodulador (oxindol alcaloides), anti-inflamatório (TNF-alfa, IL-1, IL-6), antiviral, antioxidante, reparo de DNA, antiartrítico', '300-500mg extrato (3% alcaloides) 2-3x/dia', 'Entre refeições', '8 semanas on / 4 off', ARRAY['Inflamação sistêmica crônica','Artrite por sobrecarga','Imunidade comprometida por volume de treino alto','Reparo de DNA'], ARRAY[]::text[], ARRAY[]::text[], '{"absorcao":"45-60min","meia_vida":"6-8h","pico":"2h","metabolismo":"hepático extenso"}'::jsonb),

-- 18. GARRA DO DIABO
('Harpagophytum (Garra do Diabo)', 'África do Sul — padrão europeu para dor articular', 'Inibe COX-2 e LOX, reduz TNF-alfa, IL-1β, IL-6, analgésico (harpagoside), eficácia comparável ao Ibuprofeno sem colaterais gástricos', '500-750mg extrato (2-3% harpagoside) 3x/dia', 'Com refeição leve', 'Contínuo para dor crônica articular', ARRAY['Dor articular crônica','Dor lombar','Anti-inflamatório sem colaterais gástricos'], ARRAY[]::text[], ARRAY[]::text[], '{"absorcao":"30-45min","meia_vida":"8-10h","pico":"2-3h","eliminacao":"renal e biliar"}'::jsonb),

-- 19. GINSENG SIBERIANO
('Eleutherococcus senticosus (Ginseng Siberiano)', 'Rússia/China — adaptógeno', 'Adaptógeno adrenal, melhora resistência ao estresse, performance física e cognitiva', '300-600mg extrato (0.8% eleuterosídeos) 2x/dia', 'Manhã + tarde (NUNCA à noite — estimulante)', '6-8 semanas on / 2-3 semanas off', ARRAY['Fadiga adrenal','Performance física','Resistência ao estresse','Cognição'], ARRAY[]::text[], ARRAY['Eleutherococcus + Rhodiola + Ashwagandha = Adrenal Triad'], '{"absorcao":"45-60min","meia_vida":"6-8h","pico":"2h","eliminacao":"renal"}'::jsonb),

-- 20. MACA PRETA
('Maca Preta Gelatinizada', 'Peru — versão gelatinizada superior', 'Maior concentração de macamidas (princípio ativo para energia e libido masculina). Gelatinizada: amido removido = biodisponibilidade 4x maior', '1.5-3g maca preta gelatinizada 2x/dia', 'Manhã com café ou pré-treino + tarde (não à noite — energizante)', 'Contínuo (sem dessensibilização documentada)', ARRAY['Energia','Libido masculina','Performance atlética','Hormonal'], ARRAY[]::text[], ARRAY[]::text[], '{"absorcao":"45-60min","pico":"2-3h","nota":"gelatinizada tem 4x mais biodisponibilidade que crua"}'::jsonb),

-- 21. ÓLEO DE ORÉGANO
('Óleo de Orégano (Carvacrol > 80%)', 'Mediterrâneo', 'Antimicrobiano de amplo espectro, antifúngico, antiparasitário, bactericida potente', '200mg 3x/dia', 'Entre refeições, longe de probióticos (esperar 2h)', 'Máximo 4 semanas (bactericida amplo)', ARRAY['SIBO','Disbiose','Candidíase','Parasitoses','Antimicrobiano'], ARRAY['Uso prolongado > 4 semanas'], ARRAY['Separar 2-3h de probióticos'], '{"absorcao":"30-45min","meia_vida":"4-6h","pico":"1-2h"}'::jsonb),

-- 22. PAU D''ARCO
('Pau D''Arco (Tabebuia impetiginosa)', 'Amazônia — Brasil', 'Antifúngico, antiparasitário, imunomodulador, anti-inflamatório', 'Chá: 10g em 1L água ferver 20min, 3 xícaras/dia. Extrato: 500mg 3x/dia', 'Entre refeições', 'Conforme protocolo antimicrobiano', ARRAY['Candidíase','Parasitoses','Imunomodulação','Infecções fúngicas'], ARRAY[]::text[], ARRAY[]::text[], '{"absorcao":"30-60min","meia_vida":"4-6h"}'::jsonb),

-- 23. MÁSTIQUE
('Mástique (Pistacia lentiscus)', 'Grécia — goma de mástique', 'Erradicação comprovada de H. pylori, protetor gástrico, anti-inflamatório', '1g 2x/dia', 'Jejum (manhã) + antes de dormir', '8-12 semanas para erradicação', ARRAY['H. pylori','Gastrite','Úlcera gástrica','Proteção mucosa'], ARRAY[]::text[], ARRAY['Lactoferrina 200mg + Sulforafano 100mg + Vitamina C 1000mg = protocolo H. pylori completo'], '{"absorcao":"30-45min","meia_vida":"6-8h"}'::jsonb),

-- 24. POLICOSANOL
('Policosanol', 'Cana-de-açúcar ou cera de abelha — Cuba', 'Inibe síntese hepática de colesterol, mecanismo similar a estatinas mas natural', '20-40mg/dia', 'NOITE (síntese de colesterol é máxima entre 00h-06h)', 'Contínuo', ARRAY['LDL alto','Colesterol total elevado','Alternativa natural a estatinas'], ARRAY[]::text[], ARRAY['Reduz LDL até 24% em estudos cubanos'], '{"absorcao":"30-60min","meia_vida":"8-12h","timing_critico":"noturno — síntese hepática noturna"}'::jsonb),

-- 25. BERGAMOTA
('Bergamota (Citrus bergamia)', 'Calábria, Itália', 'Inibe HMG-CoA redutase (igual estatina) sem colaterais musculares, anti-inflamatório, antioxidante', '500-1000mg extrato (BPF 38%)', 'Manhã em jejum', 'Contínuo', ARRAY['LDL alto (reduz até 36% em 30 dias)','Colesterol','Triglicerídeos','Alternativa a estatinas'], ARRAY[]::text[], ARRAY[]::text[], '{"absorcao":"30-45min","meia_vida":"6-8h","pico":"2h"}'::jsonb);
