ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS coach_notes TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_by UUID;