
-- 1. Estender meridian_plans para suportar estratégia BUILD/MAINTENANCE
ALTER TABLE public.meridian_plans
  ADD COLUMN IF NOT EXISTS plan_strategy TEXT NOT NULL DEFAULT 'CUT'
    CHECK (plan_strategy IN ('CUT','BUILD','MAINTENANCE')),
  ADD COLUMN IF NOT EXISTS build_phase_start_date DATE,
  ADD COLUMN IF NOT EXISTS refine_phase_start_date DATE,
  ADD COLUMN IF NOT EXISTS projected_lean_gain_kg DECIMAL(5,2),
  ADD COLUMN IF NOT EXISTS projected_fat_loss_kg DECIMAL(5,2);

ALTER TABLE public.meridian_plans
  ALTER COLUMN diet_phase_start_date DROP NOT NULL,
  ALTER COLUMN hard_cut_start_date DROP NOT NULL;

COMMENT ON COLUMN public.meridian_plans.plan_strategy IS
  'CUT = atleta acima do peso de palco, fases tradicionais. BUILD = atleta abaixo, fases de construção. MAINTENANCE = lifestyle puro.';

-- 2. Re-seed idempotente de meridian_default_parameters (22 perfis base)
INSERT INTO public.meridian_default_parameters (
  biological_sex, athlete_track, category, age_group,
  stage_bf_min, stage_bf_max,
  has_weight_cap, weight_cap_table,
  diet_phase_loss_min, diet_phase_loss_max,
  hard_cut_loss_min, hard_cut_loss_max,
  pre_prep_weeks_default, buffer_weeks_min, buffer_weeks_recommended,
  final_sharpening_weeks_default,
  reverse_diet_weeks_min, reverse_diet_weeks_recommended,
  min_weeks_between_peaks,
  recovery_multiplier,
  required_health_markers,
  red_flag_thresholds,
  cycle_sync_recommended, amenorrhea_is_red_flag,
  glute_specialization_required,
  routine_practice_required, routine_practice_weeks_before_stage,
  notes
) VALUES
('MALE','ENHANCED','OPEN_BODYBUILDING','OPEN',3.00,5.00,false,NULL,0.70,0.90,0.90,1.10,4,2,3,3,4,6,6,1.00,
 ARRAY['tsh','t3','t4','cortisol_morning','lipid_panel','hematocrit','liver_enzymes'],
 '{"tsh":{"max":4.0},"hematocrit":{"max":54}}'::jsonb,false,false,false,false,NULL,
 'Bodybuilding Open Enhanced — sem cap de peso.'),
('MALE','ENHANCED','CLASSIC_PHYSIQUE','OPEN',4.00,6.00,true,
 '{"by_height_cm":[{"max":165,"cap_kg":72.6},{"max":170,"cap_kg":77.1},{"max":175,"cap_kg":81.6},{"max":180,"cap_kg":87.1},{"max":185,"cap_kg":93.9},{"max":190,"cap_kg":102.0},{"max":999,"cap_kg":105.2}]}'::jsonb,
 0.70,0.90,0.90,1.10,4,2,3,3,4,6,6,1.00,
 ARRAY['tsh','t3','t4','cortisol_morning','lipid_panel','hematocrit'],
 '{"tsh":{"max":4.0}}'::jsonb,false,false,false,false,NULL,'Classic Physique Enhanced — cap por altura aplicado.'),
('MALE','ENHANCED','MENS_PHYSIQUE','OPEN',5.00,7.00,false,NULL,0.60,0.80,0.80,1.00,4,2,3,3,4,6,6,1.00,
 ARRAY['tsh','t3','t4','cortisol_morning','lipid_panel'],
 '{"tsh":{"max":4.0}}'::jsonb,false,false,false,false,NULL,'Men''s Physique Enhanced.'),
('MALE','ENHANCED','BODYBUILDING_212','OPEN',3.00,5.00,true,'{"global_cap_kg":96.2}'::jsonb,
 0.70,0.90,0.90,1.10,4,2,3,3,4,6,6,1.00,
 ARRAY['tsh','t3','t4','cortisol_morning','lipid_panel','hematocrit'],
 '{"tsh":{"max":4.0},"hematocrit":{"max":54}}'::jsonb,false,false,false,false,NULL,'212 Bodybuilding Enhanced — cap global 96.2 kg.'),
('MALE','NATURAL','OPEN_BODYBUILDING','OPEN',4.00,6.00,false,NULL,0.40,0.60,0.60,0.80,6,4,4,3,12,16,16,1.00,
 ARRAY['tsh','t3','t4','total_testosterone','free_testosterone','lh','fsh','estradiol_male','shbg','cortisol_morning','lipid_panel','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"total_testosterone":{"min":300}}'::jsonb,false,false,false,false,NULL,'Open BB Natural — janela mínima 24 sem.'),
('MALE','NATURAL','CLASSIC_PHYSIQUE','OPEN',5.00,7.00,true,
 '{"by_height_cm":[{"max":165,"cap_kg":72.6},{"max":170,"cap_kg":77.1},{"max":175,"cap_kg":81.6},{"max":180,"cap_kg":87.1},{"max":185,"cap_kg":93.9},{"max":190,"cap_kg":102.0},{"max":999,"cap_kg":105.2}]}'::jsonb,
 0.40,0.60,0.60,0.80,6,4,4,3,12,16,16,1.00,
 ARRAY['tsh','t3','t4','total_testosterone','free_testosterone','lh','fsh','estradiol_male','shbg','cortisol_morning','lipid_panel','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"total_testosterone":{"min":300}}'::jsonb,false,false,false,false,NULL,'Classic Physique Natural.'),
('MALE','NATURAL','MENS_PHYSIQUE','OPEN',6.00,8.00,false,NULL,0.40,0.60,0.60,0.80,6,4,4,3,12,16,16,1.00,
 ARRAY['tsh','t3','t4','total_testosterone','free_testosterone','lh','fsh','estradiol_male','cortisol_morning','lipid_panel','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"total_testosterone":{"min":300}}'::jsonb,false,false,false,false,NULL,'Men''s Physique Natural.'),
('FEMALE','ENHANCED','BIKINI','OPEN',10.00,13.00,false,NULL,0.50,0.70,0.70,0.90,4,3,3,3,6,8,8,1.00,
 ARRAY['tsh','t3','t4','estradiol_female','progesterone','lh','fsh','prolactin','cortisol_morning','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"ferritin":{"min":30},"vitamin_d":{"min":30}}'::jsonb,true,false,true,false,NULL,'Bikini Enhanced — glúteo specialization.'),
('FEMALE','ENHANCED','WELLNESS','OPEN',12.00,15.00,false,NULL,0.50,0.70,0.70,0.90,4,3,3,3,6,8,8,1.00,
 ARRAY['tsh','t3','t4','estradiol_female','progesterone','lh','fsh','prolactin','cortisol_morning','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"ferritin":{"min":30},"vitamin_d":{"min":30}}'::jsonb,true,false,true,false,NULL,'Wellness Enhanced — glúteo/coxa specialization.'),
('FEMALE','ENHANCED','FIGURE','OPEN',8.00,12.00,false,NULL,0.50,0.70,0.70,0.90,4,3,3,3,6,8,8,1.00,
 ARRAY['tsh','t3','t4','estradiol_female','progesterone','lh','fsh','prolactin','cortisol_morning','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"ferritin":{"min":30}}'::jsonb,true,false,false,false,NULL,'Figure Enhanced.'),
('FEMALE','ENHANCED','WOMENS_PHYSIQUE','OPEN',7.00,10.00,false,NULL,0.50,0.70,0.70,0.90,4,3,3,3,6,8,8,1.00,
 ARRAY['tsh','t3','t4','estradiol_female','progesterone','lh','fsh','prolactin','cortisol_morning','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"ferritin":{"min":30}}'::jsonb,true,false,false,false,NULL,'Women''s Physique Enhanced.'),
('FEMALE','ENHANCED','WOMENS_BODYBUILDING','OPEN',6.00,9.00,false,NULL,0.50,0.70,0.70,0.90,4,3,3,3,6,8,8,1.00,
 ARRAY['tsh','t3','t4','estradiol_female','progesterone','lh','fsh','prolactin','cortisol_morning','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"ferritin":{"min":30}}'::jsonb,true,false,false,false,NULL,'Women''s Bodybuilding Enhanced.'),
('FEMALE','ENHANCED','FITNESS','OPEN',8.00,11.00,false,NULL,0.50,0.70,0.70,0.90,4,3,3,3,6,8,8,1.00,
 ARRAY['tsh','t3','t4','estradiol_female','progesterone','lh','fsh','prolactin','cortisol_morning','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"ferritin":{"min":30}}'::jsonb,true,false,false,true,16,'Fitness Enhanced — routine practice 16 sem antes.'),
('FEMALE','NATURAL','BIKINI','OPEN',12.00,16.00,false,NULL,0.30,0.50,0.50,0.70,6,4,4,3,8,12,16,1.00,
 ARRAY['tsh','t3','t4','estradiol_female','progesterone','lh','fsh','prolactin','total_testosterone','cortisol_morning','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"free_testosterone":{"min":1.0},"estradiol_female":{"min":30},"ferritin":{"min":30},"vitamin_d":{"min":30}}'::jsonb,
 true,true,true,false,NULL,'Bikini Natural — amenorrhea red flag.'),
('FEMALE','NATURAL','WELLNESS','OPEN',14.00,17.00,false,NULL,0.30,0.50,0.50,0.70,6,4,4,3,8,12,16,1.00,
 ARRAY['tsh','t3','t4','estradiol_female','progesterone','lh','fsh','prolactin','cortisol_morning','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"estradiol_female":{"min":30},"ferritin":{"min":30}}'::jsonb,true,true,true,false,NULL,'Wellness Natural.'),
('FEMALE','NATURAL','FIGURE','OPEN',10.00,14.00,false,NULL,0.30,0.50,0.50,0.70,6,4,4,3,8,12,16,1.00,
 ARRAY['tsh','t3','t4','estradiol_female','progesterone','lh','fsh','prolactin','cortisol_morning','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"estradiol_female":{"min":30},"ferritin":{"min":30}}'::jsonb,true,true,false,false,NULL,'Figure Natural.'),
('FEMALE','NATURAL','WOMENS_PHYSIQUE','OPEN',9.00,12.00,false,NULL,0.30,0.50,0.50,0.70,6,4,4,3,8,12,16,1.00,
 ARRAY['tsh','t3','t4','estradiol_female','progesterone','lh','fsh','prolactin','cortisol_morning','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"estradiol_female":{"min":30},"ferritin":{"min":30}}'::jsonb,true,true,false,false,NULL,'Women''s Physique Natural.'),
('FEMALE','NATURAL','WOMENS_BODYBUILDING','OPEN',8.00,11.00,false,NULL,0.30,0.50,0.50,0.70,6,4,4,3,8,12,16,1.00,
 ARRAY['tsh','t3','t4','estradiol_female','progesterone','lh','fsh','prolactin','cortisol_morning','ferritin','vitamin_d'],
 '{"tsh":{"max":4.0},"estradiol_female":{"min":30},"ferritin":{"min":30}}'::jsonb,true,true,false,false,NULL,'Women''s Bodybuilding Natural.'),
('MALE','LIFESTYLE','OPEN_BODYBUILDING','OPEN',10.00,14.00,false,NULL,0.40,0.60,0.50,0.70,3,2,2,2,4,6,999,1.00,
 ARRAY['tsh','lipid_panel','glucose'],
 '{}'::jsonb,false,false,false,false,NULL,'Lifestyle MALE — mini-cuts.'),
('FEMALE','LIFESTYLE','BIKINI','OPEN',16.00,22.00,false,NULL,0.30,0.50,0.40,0.60,3,2,2,2,4,6,999,1.00,
 ARRAY['tsh','ferritin','vitamin_d'],
 '{"ferritin":{"min":30}}'::jsonb,true,true,false,false,NULL,'Lifestyle FEMALE — Photo Week branda.')
ON CONFLICT (biological_sex, athlete_track, category, age_group) DO UPDATE SET
  stage_bf_min = EXCLUDED.stage_bf_min,
  stage_bf_max = EXCLUDED.stage_bf_max,
  has_weight_cap = EXCLUDED.has_weight_cap,
  weight_cap_table = EXCLUDED.weight_cap_table,
  diet_phase_loss_min = EXCLUDED.diet_phase_loss_min,
  diet_phase_loss_max = EXCLUDED.diet_phase_loss_max,
  hard_cut_loss_min = EXCLUDED.hard_cut_loss_min,
  hard_cut_loss_max = EXCLUDED.hard_cut_loss_max,
  pre_prep_weeks_default = EXCLUDED.pre_prep_weeks_default,
  buffer_weeks_min = EXCLUDED.buffer_weeks_min,
  buffer_weeks_recommended = EXCLUDED.buffer_weeks_recommended,
  final_sharpening_weeks_default = EXCLUDED.final_sharpening_weeks_default,
  reverse_diet_weeks_min = EXCLUDED.reverse_diet_weeks_min,
  reverse_diet_weeks_recommended = EXCLUDED.reverse_diet_weeks_recommended,
  min_weeks_between_peaks = EXCLUDED.min_weeks_between_peaks,
  recovery_multiplier = EXCLUDED.recovery_multiplier,
  required_health_markers = EXCLUDED.required_health_markers,
  red_flag_thresholds = EXCLUDED.red_flag_thresholds,
  cycle_sync_recommended = EXCLUDED.cycle_sync_recommended,
  amenorrhea_is_red_flag = EXCLUDED.amenorrhea_is_red_flag,
  glute_specialization_required = EXCLUDED.glute_specialization_required,
  routine_practice_required = EXCLUDED.routine_practice_required,
  routine_practice_weeks_before_stage = EXCLUDED.routine_practice_weeks_before_stage,
  notes = EXCLUDED.notes;
